--- #YAML:1.0
name:               Devel-Pragma
version:            0.53
abstract:           helper functions for developers of lexical pragmas
author:
    - chocolateboy <chocolate@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    B::Hooks::OP::Annotation:  0.32
    B::Hooks::OP::Check:  0.15
    ExtUtils::Depends:    0.301
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::EndOfScope:  0.07
    B::Hooks::OP::Annotation:  0.32
    B::Hooks::OP::Check:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
