---
abstract: 'helper functions for developers of lexical pragmas'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Pragma
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  Lexical::SealRequireHints: '0.010'
  perl: '5.008001'
resources:
  bugtracker: http://github.com/chocolateboy/Devel-Pragma/issues
  repository: http://github.com/chocolateboy/Devel-Pragma
version: 1.1.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
