---
abstract: 'helper functions for developers of lexical pragmas'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  B::Hooks::OP::Annotation: 0.44
  B::Hooks::OP::Check: 0.19
  ExtUtils::Depends: 0.302
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Pragma
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::OP::Annotation: 0.44
  B::Hooks::OP::Check: 0.19
  Lexical::SealRequireHints: 0.007
resources:
  repository: http://github.com/chocolateboy/Devel-Pragma
version: 0.60
